fix: don't hardcode /usr/bin path
linuxdeepin/deepin-screen-recorder pull request #227
Opened 2022-09-16 09:02 UTC by wineee

Log: 避免硬编码查找路径，提高可移植性

2022-09-27 07:31 UTC, wineee commented
CC @HeeMingYang

2022-09-27 07:33 UTC, wineee commented on src/main.cpp
>              flag = false;
这里有个问题， 之前判断 libavcodec.so.58 已经设置了一次 flag，!isWaylandProtocol() 的情况下不需要对 libavcodec.so.58 的判断吗？

2022-10-17 03:06 UTC, hundundadi commented on src/main.cpp
>              flag = false;
不需要了哈，x11下只需要判断是否存在ffmpeg，不存在直接走gstreamer

2022-10-17 03:38 UTC, wineee commented on src/main.cpp
>              flag = false;
> 不需要了哈，x11下只需要判断是否存在ffmpeg，不存在直接走gstreamer
libavcodec 也是 ffmpeg 的库吧？

2022-12-13 05:42 UTC, wineee commented
@hundundadi 这个还不能合吗？

2023-01-03 07:51 UTC, hundundadi reviewed
[是否满足兼容性要求] Y
[是否满足commit提交规范] Y
[是否满足编码规范] Y
[Review结论] Pass
[Fail原因] N/A

2023-01-03 09:14 UTC, justforlxz requested changes

2023-01-03 09:14 UTC, justforlxz commented on src/main.cpp
> +        if (!QStandardPaths::findExecutable("ffmpeg").isEmpty()) {
直接 `flag = !QStandardPaths::findExecutable("ffmpeg").isEmpty()` 不就好了 😆

2023-01-30 03:29 UTC, lzwind approved these changes
/+1

2023-01-30 05:17 UTC, wineee commented
deepin-screen-recorder 升级到 v23 后，此 pr 已经无法合并，有很多需要调整之处，我会重新整理另提 pr

2023-01-30 05:17 UTC, closed without merging

2023-01-31 02:04 UTC, wineee commented
转到 https://github.com/linuxdeepin/deepin-screen-recorder/pull/306